[package]
name = "the-super-tiny-compiler-in-rust"
version = "0.1.0"
authors = ["Philipp Hansch <dev@phansch.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
